version: '3.9'
services:
  node:
    build:
      context: .
    command: npm run test
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

